title: Amr Bakouban's Blog
theme: minima
author: Amr Bakouban
email: abako2@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
My name is Amr Bakouban and this is a blog I wrote about me
# social links
github_username:amrbakouban# DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
